; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
; WICHTIG: Mehr RAM für den neuen I2S-Treiber + Webserver
board_build.partitions = min_spiffs.csv     ; oder "default.csv" ausprobieren
board_build.f_cpu = 240000000
board_build.flash_mode = dio

build_flags = 
	-DENABLE_DATABASE
	-DFIREBASE_SSE_TIMEOUT_MS=40000
	-DFIREBASE_JWT_TIMEOUT_MS=60000
    -D CONFIG_ESP_SYSTEM_MEMPROT_FEATURE=0
    -D CORE_DEBUG_LEVEL=0
    -O2                              ; Optimierung einschalten
    -Wl,--gc-sections                ; ungenutzten Code entfernen

	
lib_deps = 
    ;adafruit/DHT sensor library@^1.4.4
    ;adafruit/Adafruit Unified Sensor@^1.1.14

    arduinoFFT
	bblanchon/ArduinoJson


build_src_filter =
    +<*.cpp>
    +<*.h>
    -<dht22_sensor.cpp>
    -<dht22_sensor.h>
	-<main-blink-und-wifi.txt>
	-<test.cpp>
    
	
		
	
