; PlatformIO Project Configuration File
[platformio]
default_envs = esp32dev

[env]
build_src_filter =
    +<*.cpp>
    +<*.h>
    -<dht22_sensor.cpp>
    -<dht22_sensor.h>
    -<main-blink-und-wifi.txt>
    -<test.cpp>

lib_deps = 
    arduinoFFT
    bblanchon/ArduinoJson
    adafruit/Adafruit AHTX0
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor

build_flags = 
    -DENABLE_DATABASE
    -DFIREBASE_SSE_TIMEOUT_MS=40000
    -DFIREBASE_JWT_TIMEOUT_MS=60000
    -D CONFIG_ESP_SYSTEM_MEMPROT_FEATURE=0
    -D CORE_DEBUG_LEVEL=0
    -O2
    -Wl,--gc-sections

; =============================================
; Echter ESP32 (Hardware)
; =============================================
[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.partitions = min_spiffs.csv
board_build.f_cpu = 240000000
board_build.flash_mode = dio


; =============================================
; Wokwi Simulation
; =============================================
[env:wokwi]
extends = env:esp32dev
build_flags = 
    ${env.build_flags}          ; ← alle Flags aus [env] übernehmen
    -DSIMULATION=1              ; ← nur das zusätzliche Define für Simulation